name: 'Cancel Multi Action'
description: 'Cancel the Action, if it is from this repository, so it is not run a second time.'
inputs:
  token:
    description: 'Token'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'

